name: bioinformatics_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.1
  - r-tidyverse
  - bioconductor-annotationhub
  - bioconductor-regioner
  - bioconductor-chippeakanno

  - bcftools
  - samtools
  - python
  - pandas
  - pybigwig
